baseURL: "https://im0j.github.io"
languageCode: ko
defaultContentLanguage: ko
title: im0j.me
theme: PaperMod

canonifyURLs: true
enableInlineShortcodes: true
enableRobotsTXT: true

languages:
  ko:
    languageName: "í•œêµ­ì–´"
    weight: 10
    menu:
      main:
        - name: í¬ìŠ¤íŠ¸
          url: posts/
          weight: 10
        - name: ì•„ì¹´ì´ë¸Œ
          url: archives/
          weight: 20
        - name: ê²€ìƒ‰
          url: search/
          weight: 30
        - name: íƒœê·¸
          url: tags/
          weight: 40
  en:
    languageName: "English"
    weight: 20
    profileMode:
      enabled: true
      title: "Hi there! ğŸ‘‹"
      subtitle: Welcome to my blog.
      buttons:
        - name: About me
          url: about/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  # description: "im0j.me"
  # author: ì„ì˜ì¤€

  ShowReadingTime: true

  homeInfoParams:
    Title: "ì•ˆë…•í•˜ì„¸ìš”! ğŸ‘‹"
    Content: ì œ ë¸”ë¡œê·¸ì— ì˜¤ì‹  ê²ƒì„ í™˜ì˜í•©ë‹ˆë‹¤.
  socialIcons:
    - name: github
      url: 'https://github.com/im0j'
    - name: twitter
      url: 'https://twitter.com/im0j21'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/8516513/im0j'
    - name: email
      url: 'mailto:im.youngjun.21@gmail.com'
  assets:
    disableHLJS: true

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    style: monokailight
    noClasses: false
